version: '3.4'

services:
  location.crqs.db:
    image: postgres
    container_name: location.crqs.db
    environment:     
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=borda
      - POSTGRES_DB=locationcrqsdb
      - ALLOW_IP_RANGE='0.0.0.0/0'
      - TZ=Asia/Istanbul
    ports:
      - "5432:5432"
    volumes:
       - postgresdb:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: location.crqs.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-borda}
    ports:
      - "${PGADMIN_PORT:-5060}:80"
    volumes:
       - pgadmin:/var/lib/pgadmin 
    depends_on:
      - "location.crqs.db"

  location.crqs.api:
    image: ${DOCKER_REGISTRY-}locationcrqsapi
    environment:
      - TZ=Asia/Istanbul
      #- SSL_CERT_DIR=/dev/null
    build:
      context: .
      dockerfile: Location.Service.Api/Dockerfile
    depends_on:
      - "location.crqs.db"
    ports:
      - "32400:80"

volumes:
  postgresdb:
  pgadmin: